#!/bin/sh

# Set these paths appropriately

BIN=/Users/cybor/Sites/3n-tools/python/tree-tagger/bin
CMD=/Users/cybor/Sites/3n-tools/python/tree-tagger/cmd
LIB=/Users/cybor/Sites/3n-tools/python/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/english-abbreviations
PARFILE=${LIB}/english-utf8.par

$TOKENIZER -e -a $ABBR_LIST $* |
# remove empty lines
grep -v '^$' |
# tagging
$TAGGER $OPTIONS $PARFILE | 
perl -pe 's/\tV[BDHV]/\tVB/;s/\tIN\/that/\tIN/;'
